// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxjuoqgkthqdyaevhqaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4anVvcWdrdGhxZHlhZXZocWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTE2MjcsImV4cCI6MjA2Nzk2NzYyN30.q1j6XaNvCpluA_TgF7gYVgNiu7-EAd4se5QQFUNVkp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});